stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn deploy -s ci_settings.xml
  only:
    - main
    - tags